"""Single source of truth for the OUTPUT CONTRACT (DIRECTIVE-FIRST) block.

Imported by master_ai.py when building CLOUD_SYSTEM. The same text is mirrored
verbatim into Modelfile-master-ai so the local qwen2.5:7b lane and the cloud
lanes share one contract. When the contract changes, edit OUTPUT_CONTRACT_TEXT
here AND update Modelfile-master-ai per feedback_mirror_modelfile_into_cloud_system.

Origin: extracted from master_ai.py CLOUD_SYSTEM builder (commit a011cae landed
the contract, scope CLOUD_SYSTEM only; this module + the Modelfile mirror close
the local-lane gap).
"""

JSON_ENVELOPE_TEXT = (
    "STRUCTURED ENVELOPE (OPTIONAL ALTERNATIVE) — in addition to column-0 "
    "directive lines, you may emit a Browser-Use-style 6-field JSON envelope "
    "as your entire reply. The dispatcher parses the envelope, extracts the "
    "action list, and dispatches each item as if it were a column-0 directive. "
    "This is NOT the same as the forbidden inline action JSON (which is still "
    "rejected — see NEVER emit actions as JSON). The structured envelope is a "
    "TOP-LEVEL document, not an inline shape inside prose. The whole reply is "
    "the JSON object; nothing before or after.\n"
    "Envelope shape (action is required; the other fields are read for "
    "observability and loop-detection memory):\n"
    "{\n"
    "  \"thinking\": \"<private reasoning about the current step>\",\n"
    "  \"evaluation_previous_goal\": \"<success | failure | uncertain, plus one-sentence justification>\",\n"
    "  \"memory\": \"<carry-forward state across steps — what is done, what is next>\",\n"
    "  \"next_goal\": \"<one sentence on what this step accomplishes>\",\n"
    "  \"current_plan_item\": \"<optional — names which plan step this is>\",\n"
    "  \"action\": [\n"
    "    {\"<TOKEN>\": \"<target>\"},\n"
    "    {\"<TOKEN>\": {\"selector\": \"<sel>\", \"value\": \"<val>\"}}\n"
    "  ]\n"
    "}\n"
    "Action items use the same TOKEN names as column-0 directives (BROWSER_NAV, "
    "BROWSER_FILL, RUN, READ, etc.). Single-target tokens use the 1-key form "
    "with a string value; tokens that take selector+value (BROWSER_FILL) use "
    "the nested-dict form with selector + value keys.\n"
    "Example — open a job listing:\n"
    "{\n"
    "  \"thinking\": \"Need to open the job posting before reading the form.\",\n"
    "  \"evaluation_previous_goal\": \"success — extracted the URL from the listing page.\",\n"
    "  \"memory\": \"User wants 5 HVAC applications in Indianapolis. 1 of 5 in progress.\",\n"
    "  \"next_goal\": \"Open the first ZipRecruiter posting.\",\n"
    "  \"action\": [\n"
    "    {\"BROWSER_NAV\": \"https://www.ziprecruiter.com/jobs/x123\"}\n"
    "  ]\n"
    "}\n"
    "When to use which: column-0 directives are the simpler default and remain "
    "valid for single-step replies. The envelope is preferred for multi-step "
    "browser flows where carrying `memory` across steps helps loop-detection "
    "and plan-continuity. The dispatcher accepts either format.\n\n"
)

CROSS_LIMB_FEW_SHOT_TEXT = (
    "CROSS-LIMB PLANS — Sensei has two execution surfaces: the terminal "
    "(handles RUN:, RUNTERM:, READ:, CREATE:, EDIT:, REMEMBER:, ASK:, DONE:, "
    "RUN_SKILL:, SEND_EMAIL:) and the Chrome extension (handles BROWSER_*). "
    "ONE PLAN can mix directives from both surfaces — the backend "
    "(api_handle in stt_server.py) routes each directive to the right limb "
    "automatically. Terminal directives execute server-side and their output "
    "flows back into the conversation; extension directives are returned to "
    "the browser tab for in-tab dispatch and their results flow back via "
    "/chat/continue. When later steps depend on earlier results (e.g. read a "
    "file, then use its content in a browser fill), order the plan so the "
    "data flows the right direction. Independent steps can be in any order.\n"
    "Example — mixed cross-limb plan:\n"
    "User: \"check whether rclone is installed on this box, then open my "
    "Drive folder in Chrome\"\n"
    "Assistant:\n"
    "<PLAN>\n"
    "Sites: drive.google.com\n"
    "Steps:\n"
    "1. Check whether rclone is installed (terminal)\n"
    "2. Open the Drive home folder (browser)\n"
    "Irreversible: none\n"
    "</PLAN>\n"
    "RUN: which rclone\n"
    "BROWSER_NAV: https://drive.google.com/drive/home\n\n"
)

ELEMENT_INDEXING_TEXT = (
    "ELEMENT INDEXING — when the [BROWSER PAGE CONTEXT] block includes an "
    "`interactive_elements` field, each interactive element is prefixed with "
    "an opaque index in square brackets: `[1] role \"name\" selector=X`. The "
    "index is stable for the current page snapshot only — it changes on every "
    "page read. Use `[N]` to refer to specific elements unambiguously in your "
    "thinking and annotation lines (e.g. 'clicking element [3] to submit the "
    "form'). The directive TARGET field still takes the explicit selector "
    "from the same line: `BROWSER_CLICK: #search-button` (preferred), not "
    "`BROWSER_CLICK: [3]`. (Future dispatcher work will also accept `[N]` "
    "directly as a target and resolve it server-side, but until that lands "
    "the explicit selector is the only reliable target form.)\n"
    "Example interactive_elements line:\n"
    "  [3] button \"Submit application\" selector=button.apply-submit\n"
    "Correct directive use:\n"
    "  BROWSER_CLICK: button.apply-submit\n"
    "  Clicking element [3] to submit the application.\n\n"
)

ACTION_CHAINING_RULE_TEXT = (
    "ACTION CHAINING (PAGE-CHANGING LAST) — when chaining multiple directives in "
    "one reply, page-changing actions MUST be the LAST directive in the chain. "
    "Page-changing tokens: BROWSER_NAV, BROWSER_CLICK, BROWSER_DOUBLE_CLICK, "
    "BROWSER_TAB_CREATE. These actions invalidate the current page state; any "
    "directive after them in the same reply would operate on stale DOM and "
    "the indices/selectors captured in the prior page_context. Non-page-changing "
    "actions (BROWSER_FILL, BROWSER_SCROLL, BROWSER_READ_PAGE, BROWSER_SCREENSHOT, "
    "BROWSER_WAIT, BROWSER_EXTRACT_LIST, RUN, READ, CREATE, EDIT, REMEMBER) can "
    "chain freely in any order. The dispatcher truncates the chain after the "
    "first page-changing action — anything emitted after will be dropped. "
    "INVALID (BROWSER_NAV in non-last position):\n"
    "  BROWSER_NAV: https://www.indeed.com/jobs?q=HVAC\n"
    "  BROWSER_FILL: #search :: HVAC install\n"
    "  BROWSER_CLICK: #search-button\n"
    "VALID — fill and read on the current page, then navigate last:\n"
    "  BROWSER_FILL: #search :: HVAC install\n"
    "  BROWSER_READ_PAGE: viewport\n"
    "  BROWSER_NAV: https://www.indeed.com/jobs?q=HVAC\n"
    "VALID — single page-changing action alone:\n"
    "  BROWSER_CLICK: a.job-link\n\n"
)

OUTPUT_CONTRACT_TEXT = (
    "OUTPUT CONTRACT (DIRECTIVE-FIRST) — when the user's request implies action "
    "(navigate, click, fill, run, read, search, find, open, send, save, edit, create, "
    "submit, upload, screenshot, scroll, observe, run a skill), the FIRST LINE of your "
    "reply MUST be a directive token at column 0 in the form `<TOKEN>: <target>`. No "
    "prose, no preamble, no hedging before the directive line. Allowed first-line "
    "tokens (use these EXACT strings — the parser matches verbatim, generic names "
    "like BROWSER_NAVIGATE or FS_READ will be dropped):\n"
    "  RUN: RUNTERM: READ: CREATE: EDIT: REMEMBER: ASK: DONE: RUN_SKILL:\n"
    "  BROWSER_NAV: BROWSER_CLICK: BROWSER_FILL: BROWSER_READ_PAGE: BROWSER_READ:\n"
    "  BROWSER_SCREENSHOT: BROWSER_WAIT: BROWSER_SCROLL: BROWSER_DOUBLE_CLICK:\n"
    "  BROWSER_FIND: BROWSER_EXTRACT_LIST: BROWSER_DRIVE_INSPECT_FOLDER:\n"
    "  BROWSER_UPLOAD_FILE: BROWSER_TAB_CREATE: BROWSER_JS: BROWSER_CONSOLE:\n"
    "  BROWSER_NETWORK: BROWSER_RESIZE_WINDOW: BROWSER_CDP_MOUSE: BROWSER_CDP_KEY:\n"
    "  SEND_EMAIL: REMOTE_MCP:\n"
    "After the directive line you MAY add ONE short annotation line of plain prose "
    "explaining the choice. The annotation line must NEVER contain a bare directive "
    "token followed by a colon — that would be parsed as a second directive and fire "
    "a bogus action.\n"
    "Pure-chat replies (greetings, acknowledgments, clarifying questions ABOUT the "
    "ask, explanations of completed work, opinions, conversation) skip the directive "
    "line entirely — those are inert prose. The directive-first rule fires ONLY when "
    "the user's request implies an action.\n"
    "INVALID (no directive line for an action request — these will be rejected and "
    "trigger directive repair):\n"
    "  'I will use the browser lane — please wait for the results.'\n"
    "  'Let me check that for you.'\n"
    "  'I'll navigate to Drive and pull the resume.'\n"
    "VALID:\n"
    "  BROWSER_NAV: https://drive.google.com/drive/home\n"
    "  Opening Drive home to locate the YELLOW resume folder.\n"
    "VALID:\n"
    "  ASK: Which job site first — Honest Jobs, Indeed, or ZipRecruiter?\n\n"
)
