"""{{NAME}} — generated by AppForge on {{GENERATED_AT}}.

{{TAGLINE}}

Run:
    pip install -r requirements.txt
    python app.py
    → open http://localhost:5000
"""

import json
import sqlite3
from pathlib import Path

from flask import Flask, jsonify, render_template

app = Flask(__name__)
DB = Path(__file__).parent / "data.db"


def db():
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    return conn


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/api/features")
def features():
    return jsonify(json.loads("{{FEATURES_JSON}}"))


{{AI_SNIPPET}}

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
