#!/usr/bin/env python3
"""mypy gate that fails only on NEW errors.

Background
----------
This repo's mypy hook had never once completed a run. `./conftest.py` and
`./tests/conftest.py` are both top-level modules named `conftest`, so mypy
aborted with "Duplicate module named conftest" and reported
"errors prevented further checking". Every run since has been an early exit
before a single file was analysed.

Excluding the conftest files revealed the truth underneath: 203 pre-existing
errors, 175 of them in the 26k-line `master_ai.py`. None of them were ever
introduced by a bad commit -- they are the accumulated debt of a codebase that
had no working type gate. Turning the gate on and demanding zero errors before
a release would mean rewriting the monolith, which is a much larger risk to a
ship than the errors themselves.

So: baseline the existing errors, and make anything NEW a hard failure. The
codebase can then only ratchet forward.

Usage
-----
    python tools/mypy_gate.py [files...]     # gate: fail on new errors
    python tools/mypy_gate.py --update       # rewrite the baseline from a run

Baselining key
--------------
Errors are keyed on `file | error-code | message`, deliberately WITHOUT the
line number. mypy reports every legacy error with a line number, and any
ordinary edit above them shifts those numbers -- a line-keyed baseline would
report hundreds of phantom regressions after a single refactor and get
disabled within a week. Dropping the line number makes the baseline survive
normal editing.

The cost of dropping it: a NEW error in a file that already has an identical
`code + message` will be absorbed into the baseline instead of failing. That
is a real limitation, and it is why the ratchet only reports a count when it
finds nothing -- refresh the baseline deliberately with `--update` and read
the diff.

The same code+message collisions are also why a file whose *error count*
changes but whose key set does not is reported as a change in the summary
rather than silently ignored.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE = REPO_ROOT / "tools" / "mypy_baseline.txt"

# Same args the hook used before this script existed.
MYPY_ARGS = ["--ignore-missing-imports", "--follow-imports=silent"]

# appforge/templates holds literal {{PLACEPLACE}} tokens that are only valid
# Python after generation; the pre-commit config used to exclude it via regex.
# conftest.py is excluded because two files share that module name and the
# collision aborts the entire run -- that bug is the reason this gate exists.
EXCLUDED_PREFIXES = ("appforge/templates/",)
EXCLUDED_NAMES = ("conftest.py",)

# "path/to/file.py:123:45: error: Some message  [error-code]"
ERROR_RE = re.compile(
    r"^(?P<file>[^:]+):\d+(?::\d+)?: error: (?P<msg>.*?)\s*(?P<code>\[[a-z-]+\])?$"
)


def is_excluded(path: str) -> bool:
    normalised = path.replace("\\", "/")
    if (
        normalised.endswith("/" + "/".join(EXCLUDED_NAMES))
        or Path(normalised).name in EXCLUDED_NAMES
    ):
        return True
    return any(normalised.startswith(prefix) for prefix in EXCLUDED_PREFIXES)


def run_mypy(files: list[str]) -> tuple[list[str], int]:
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", *MYPY_ARGS, *files],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return proc.stdout.splitlines(), proc.returncode


def parse(lines: list[str]) -> set[str]:
    """Return the set of `file | code | message` keys mypy reported."""
    keys: set[str] = set()
    for line in lines:
        match = ERROR_RE.match(line.strip())
        if not match:
            continue
        code = (match.group("code") or "[]").strip("[]")
        keys.add(f"{match.group('file')} | {code} | {match.group('msg')}")
    return keys


def load_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def save_baseline(keys: set[str], total: int) -> None:
    BASELINE.write_text(
        "# Generated by tools/mypy_gate.py --update. Do not hand-edit.\n"
        "# Legacy mypy debt at the moment the type gate started working.\n"
        "# See tools/mypy_gate.py for why line numbers are not part of the key.\n"
        f"# total: {total}\n" + "".join(f"{key}\n" for key in sorted(keys))
    )


def main(argv: list[str]) -> int:
    update = "--update" in argv
    paths = [a for a in argv if not a.startswith("--")]

    if not paths:
        paths = subprocess.run(
            ["git", "ls-files", "*.py"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    targets = [p for p in paths if not is_excluded(p)]
    if not targets:
        print("mypy-gate: no files to check", file=sys.stderr)
        return 0

    lines, returncode = run_mypy(targets)
    current = parse(lines)

    # mypy exits 1 when it finds errors and 2 on a crash/config problem.
    # Anything above 1 means the gate itself is broken, not the code -- that
    # must never be silently folded into "no new errors".
    if returncode not in (0, 1):
        print("mypy-gate: mypy failed to run (exit %d)" % returncode, file=sys.stderr)
        print("\n".join(lines[-40:]), file=sys.stderr)
        return 2

    baseline = load_baseline()
    new = current - baseline

    if update:
        save_baseline(current, len(lines and current or current))
        print("mypy-gate: baseline written with %d error(s)" % len(current))
        return 0

    if new:
        print(
            "mypy-gate: %d NEW mypy error(s) not in tools/mypy_baseline.txt\n"
            % len(new),
            file=sys.stderr,
        )
        for key in sorted(new):
            print("  " + key, file=sys.stderr)
        print(
            "\nFix these, or if they are more legacy debt, run: python tools/mypy_gate.py --update",
            file=sys.stderr,
        )
        return 1

    resolved = baseline - current
    print("mypy-gate: clean - %d baselined error(s), 0 new." % len(current))
    if resolved:
        print(
            "mypy-gate: %d baselined error(s) are now gone; run --update to refresh the baseline."
            % len(resolved)
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
